server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers-company
          uri: lb://customers-company
          predicate: 
            - Path=/customerc/**
        - id: customers-person
          uri: lb://customers-person
          predicate: 
            - Path=/customerp/**
        - id: account-customers
          uri: lb://account-customers
          predicate: 
            - Path=/account/**