server:
  port: 8088
spring:
  data:
    mongodb:
      uri: mongodb+srv://ehs:ehs123@cluster0.pluxt.mongodb.net/db_CreditsCustomers?retryWrites=true&w=majority
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
