server:
  port: 8086
spring:
  data:
    mongodb:
      uri: mongodb+srv://ehs:ehs123@cluster0.pluxt.mongodb.net/db_CustomersPerson?retryWrites=true&w=majority
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
    instances:
        accountCP:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        creditCP:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
resilience4j.timelimiter:
    instances:
        accountCP:
            timeoutDuration: 5s
            cancelRunningFuture: true
        creditCP:
            timeoutDuration: 2s
            cancelRunningFuture: false