server:
  port: 8086
spring:
  data:
    mongodb:
      uri: mongodb+srv://ehs:ehs123@cluster0.pluxt.mongodb.net/db_CustomersPerson?retryWrites=true&w=majority
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.23:8082/eureka/